### ISSUE TITLE
maintain external users in DB

### ISSUE THREAD

**Issue by hohwille** [oasp-forge/oasp4j-enterprise-security#1]
The access manager shall be connected with a database. External users are users accessing the application landscape from outside (internet) but do not belong to the enterprise running or owning the landscape. These external uses shall be managed in the database of the access manager.
An administrator should be able to create and modify such external user accounts.

Further it should be possible to create a self-registration so an external user can sign-up for an account himself.

**Comment by nastia2325** [comment]
In the process of creating a "Pflichtenheft" there is a question occurred. You said the administrator should be able to create and modify such external user accounts. In case the user don't sign up on himself and administrator make an registration for the user (creates a new external user). How do we want to proceed? 

The administrator creates an account with users Data (which data mandatory? E-Mail, Firstname, Lastname, Company....).

a: administrator creates a password and the user gets an Email to confirm his Account. Then he can login and change his password.

b: administrator don't create a password, but the external user gets an Email after his account is created, make a confirmation through clicking the link, then he will be asked to create his own password?

c: further proposals?

**Comment by hohwille** [comment]
Mandatory fields are
- unique login
- email
- name (first + last)

Everything else is optional.

The process depends on what is easy with the chosen tool/product. My suggestion would be that the admin only creates the account with an initial PWD. The admin is responsible how to inform the user about his login and initial password. Maybe he is capable to write an encrypted mail. On the first login the user has to change his password to proceed.

**Comment by nastia2325** [comment]
How do we want to proceed if an external user wants to login and has forgotten his password? should our system be able to handle it? in which way?

**Comment by hohwille** [comment]
The simple way is the he calls an Admin via Telephone and "authenticates" on the line and the admin resets the password and e.g. sends it via encrypted Email.
However the better approach is that a user can provide his login and his Email and request a password reset. This will verify that login and Email fit together and then generates a unique ID token with expiry and an URL from that and sends it to the Email. If the user clicks the link before expiry he can provide a new password and login with that afterwards.
