### ISSUE TITLE
Get OASP4j-example-application running on TU Server

### ISSUE THREAD

**Issue by Steph0r** [oasp-forge/oasp4j-enterprise-security#12]
Just for @yetisports , so he can see what I am up to :stuck_out_tongue_winking_eye:

**Comment by Steph0r** [comment]
The example application is now running on our VPS. The server however can only be reached from the TU Darmstadt network.

@hohwille 
Would it be possible to get a "semi-production" server at capgemini or should we look if we can rent a VPS somewhere?
My idea was to use the machine at university for testing and integration during sprints and periodically deploy working increments to a server you can access. That way we would not need full admin rights on the demo server, which might make it a little easier.

**Comment by hohwille** [comment]
Thanks for the feedback. That makes sense and I will find a solution. Maybe we can use the existing solution we already have: http://oasp-ci.cloudapp.net/ - I will check...
