### ISSUE TITLE
use internal users from directory server

### ISSUE THREAD

**Issue by hohwille** [oasp-forge/oasp4j-enterprise-security#2]
An enterprise will already have a directory server where the internal users are stored and maintained. This is typically an MS Active Directory but can also be any other system accessible via protocols like LDAP. This should be integrated (via configuration).

**Comment by nastia2325** [comment]
The administrator should be able to connect some data sources (like AD, LDAP... which sources are mandatory?) with the AM to provide the possibility for internal user to be automatically connected (via intranet) or to login (internet).

What should the admin be possible to do with this data sources or concrete users through AM either?

**Comment by hohwille** [comment]
Common requirement is that internal users are already available in AD and need to be supported by the AM. Further there must be a way to manage external users for people working with the system that do not belong to the same company. These external users need to be stored and maintained somewhere. OpenAM can connect to a directory server such as OpenDJ for such purpose. For abstraction the minimum requirement should be a directory accessible via LDAP.

**Comment by nastia2325** [comment]
How do we want to proceed if an internal user wants to login from the internet and has forgotten his password? should our system be able to handle it? in which way?
