### ISSUE TITLE
US20 Create chapter 6 "Technical environment" of the Pflichtenheft

### ISSUE THREAD

**Issue by yetisports** [oasp-forge/oasp4j-enterprise-security#24]
Create chapter 6 using the following structure:
6.1 Live system 
6.1.1   Runtime environment 
6.1.2   Client environment  
6.2 Testing environment 
6.3 Development environment

**Comment by hohwille** [comment]
We need to clarify the setup. Options:
- distributed authentication (https://docs.oracle.com/cd/E19316-01/820-3320/gcsbs/index.html)
- apache as portal using OpenAM
- tomcat as portal using OpenAM

**Comment by hohwille** [comment]
I think apache httpd as portal (https://wikis.forgerock.org/confluence/display/openam/Web+Policy+Agent+for+Apache+2.2+Installation+Guide) looks most promising on the first look. Apache httpd can be configured using mod_proxy to delegate to the backend applications.
