### ISSUE TITLE
Problem with JavaScript on Virtual Server

### ISSUE THREAD

**Issue by Steph0r** [oasp-forge/oasp4j-enterprise-security#28]
The oasp4j-example-application is deployed and running on the Virtual Private Server we got from TU.
acessing /oasp4j-example-application/ yields a 404 from tomcat saying /oasp4j-example-application/jsclient/ is not available.

I can not reproduce this on any machine except the VPS and am out of clues. Maybe some dependency I am missing?

Debian 3.2.65-1+deb7u1 x86_64
Tomcat 7.0.57

Any ideas?

**Comment by hohwille** [comment]
You are missing the jsclient that has to be build from oasp4js. This is not included by default as the oasp4j and oasp4js are somewhat separated.
See either step 10 from here:
https://github.com/oasp/oasp4j/wiki/oasp-ide-setup
also have a look here:
https://github.com/oasp/oasp4js#set-up-the-client-part-of-the-application

BTW: There is a profile "jsclient" in oasp4j-sample-server that can be used (-Pjsclient) if you previously installed oasp4js/java that will build the complete war.

**Comment by Steph0r** [comment]
Thank you for the feedback. The example application is now running nicely on the server.

It seems that deployment order makes an important difference and it only works when dragome is deploed to the server first, then oasp4j-example-application.
Does that make sense?

I am fairly new to JavaScript and learning :)

**Comment by hohwille** [comment]
Is OpenAM using dragome (Java to JavaScript compiler) or where does that come from?

Great to hear that it is working now...
