### ISSUE TITLE
US11 Setup Sample User Data Store

### ISSUE THREAD

**Issue by JuHarm89** [oasp-forge/oasp4j-enterprise-security#30]
Setup an User Data Store to connect this with OpenAM in order to retrieve sample User Data

**Comment by JuHarm89** [comment]
We (Anastasia and I) installed OpenDJ locally. OpenDJ is a free LDAP service which  is also developed by ForgeRock. We successfully connected OpenAM and OpenDJ and are now able to generate SSOToken in OpenAM for our Sample User.

**Comment by hohwille** [comment]
:+1:
