### ISSUE TITLE
Use ApacheDS instead of OpenDJ

### ISSUE THREAD

**Issue by hohwille** [oasp-forge/oasp4j-enterprise-security#34]
It would also be interesting if one can use ApacheDS instead of OpenDJ.

**Comment by hohwille** [comment]
>  If Company intends to or does use the ForgeRock Software only for the purpose(s) of developing, testing, prototyping and demonstrating its application software, then ForgeRock hereby grants Company a nonexclusive, nontransferable, limited license to use the ForgeRock Software
> only for those purposes, solely at Companys facilities and only in a non-production environment. ForgeRock may audit Companys use of the ForgeRock Software to confirm that a production license is not required upon reasonable written notice to Company. If Company intends to use the ForgeRock Software in a live environment, Company must purchase a production license and may only use
> the ForgeRock Software licensed thereunder in accordance with the terms and conditions of that subscription agreement.

This is not what you would call free open source software. 

The OpenDJ website also states:

> OpenDJ is 100% open source. You can check out the source code with SVN. The code is licensed under CDDL.

**Comment by hohwille** [comment]
The same agreement also comes with OpenAM. So what is Open about all this? The sourcecode but not the usage?

**Comment by hohwille** [comment]
https://lists.forgerock.org/pipermail/openam/2013-March/010989.html

To summarize:
1.  The source code of OpenAM is available with CDDL license (http://openam.forgerock.org/license.html).
2.  The binary from ForgeRock has a license that limits usage _without_ a subscription to “developing, testing, prototyping and/or demonstrating your application”
3.  If you want to use OpenAM in production without a ForgeRock subscription you have to build an OpenAM binary from the sources yourself.

**Comment by nastia2325** [comment]
ApacheDS is installed and connected to OpenAM.
