### ISSUE TITLE
Explore possibilities to access/validate JWT in Backend Apps

### ISSUE THREAD

**Issue by JuHarm89** [oasp-forge/oasp4j-enterprise-security#42]
Explore possibilities to access and validate the JWT in the backend applications preferably with Spring Security (integration)

**Comment by Steph0r** [comment]
I looked into this a bit on my quest to learn about spring security and figured I might as well share my little mock app for trying things out at https://github.com/Steph0r/SpringTokenPOC

What works at the moment is checking for presence and signature of a token and granting/denying access. Next step is to discriminate roles from the token to brindge the gap to issue #44 
And then of course integration into our main sample application.
