### ISSUE TITLE
support of OpenId

### ISSUE THREAD

**Issue by hohwille** [oasp-forge/oasp4j-enterprise-security#5]
As a showcase we shall also support external users to login via OpenId (http://openid.net/).

**Comment by Steph0r** [comment]
Does this mean 
1) a user can use his OpenID from elsewhere to access the system, or 
2) the system provides an OpenID for logging in somewhere else?

**Comment by hohwille** [comment]
1) was intended. Of course an admin would need to grant permission associated with the account from elsewhere.
