### ISSUE TITLE
User Details in Backend Apps

### ISSUE THREAD

**Issue by Steph0r** [oasp-forge/oasp4j-enterprise-security#50]
I understand that the backend applications should not know any users and not have any user store. 
Is that right? Or does the app need some knowledge of users or should it question the AM for user details?

**Comment by hohwille** [comment]
You understood correctly. Backend app gets user data (at least containing login/in of user) as well as permission groups of the user in the JWT from OAuth bearer header.
If the app would require showing a user profile with phone number, etc that should come from AM. But currently not yet our use-case.

**Comment by hohwille** [comment]
If that issue was for more than the question feel free to reopen and reassign.
