### ISSUE TITLE
transparent authentication for backend

### ISSUE THREAD

**Issue by hohwille** [oasp-forge/oasp4j-enterprise-security#6]
In order to make actual business applications independent of the actual authentication mechanism of the access-manager the front-end (portal / access-manager) shall proxy requests to the backend with the following requirements:
- original credentials, session-id, etc. are not present in the request to the backend
- instead the request to the backend contains a custom HTTP header containing a so called "authentication ticket" with the following aspects:
  - login of the authenticated user
  - permission groups of the authenticated user (from internal directory server, DB with external users, or in case of OpenId via OAuth).
  - validity (valid from=now / to=now+configurable validity duration)
  - signature (the content of the header is cryptographically signed with an asymmetric key)

Then a backend application only needs the public key of the access manager / portal and can verify the signature as well as the validity (requires that the times of the servers are somehow in sync - use ntpd). If the ticket is valid then the backend application can trust the login and permission groups and the user is authenticated. The permission groups can be used for authorization of the use-case/operation to perform.
If the ticket is invalid the request is rejected by the backend application.

**Comment by nastia2325** [comment]
Concerning the validity of the token, do you mean the validity duration is fix, which the admin configure, so user will be redirected to the login-view if the token is expired? Or shell the duration of the token be extended f.e. if the token is valid only xy (how much?) minutes if he make some request (without requests it would not be extended and he will be redirected)?

**Comment by ghost** [comment]
> If the ticket is invalid the request is rejected by the backend application.

We thought, that the portal will check the time span and the backend application will only check the origin of the token (whether it matches the AMs signature or not), or shall the application itself check the time span, which would be kinda rendundant, since every applicatoin would have to implement that?

Best regards,
Jonas

**Comment by hohwille** [comment]
http://jwt.io/
http://www.intridea.com/blog/2013/11/7/json-web-token-the-useful-little-standard-you-haven-t-heard-about

> which would be kinda rendundant, since every applicatoin would have to implement that?

There will be a shared library to do the actual authentication and authorization that is only plugged into each app. The thing is that this is stable and will never change. However, the actual authentication on the access level may change without touching the backend apps.

**Comment by hohwille** [comment]
Sending the token from the access systems (portal and service-gateway) to the backend apps should happen via OAuth2.0 (http://blog.cloudfoundry.org/2012/10/09/securing-restful-web-services-with-oauth2/). Technically this means the JWT is set in the HTTP header as following:

> Authorization: Bearer &lt;JWT>
