### ISSUE TITLE
avoid name clash of permission groups of different applications

### ISSUE THREAD

**Issue by hohwille** [oasp-forge/oasp4j-enterprise-security#8]
Within the access-manager the administrator has to assign all required permission groups for a user that may have access to multiple applications. The applications themselves should be quite free to define and name their permission groups. However the must be a concept to avoid name clashes so that two applications have a permission group with the same name but different semantics because the user would then either have both or none of the permissions while he should potentially only have one of them. On the other hand there might be global permissions groups that can be shared between multiple or all applications.

The easiest way to solve this is to use a prefix for each application as well as for global permission groups that is perpended to all application specific permission groups. 

An alternative to evaluate would be to organize the permission groups as children of a node (LDAP entry) for each application. Then if a request is performed from the portal (see #7) only the permission groups of that application are resolved via its node (in combination with the global permission groups). In General it should be considered that applications only receive the permission groups that actually belong to it.

**Comment by hohwille** [comment]
Farvorite solution would be to have a node/group for each application and one special node/group that is called "Shared". These nodes/groups contains the subgroups that are available to be granted to the user. The application node/group contains all the top-level groups from the access-control-schema.xml of the according application (except shared ones). And "Shared" contains all groups that are used by more that one application. Only if an application defines a group named "Shared-" followed by the name of that "Shared" group this will have a particular meaning to that application.

**Comment by hohwille** [comment]
Acceptance-Criteria: We create a permission group with the same name/identifier X for two applications A1 and A2. Then in the access-manager we give a user U the group X in A1 he should have all the according permissions in the application A1 but not the permissions of X in A2.

**Comment by JuHarm89** [comment]
One question concerning the administration of app-specific groups. Should the app-specific groups be defined in the Access Manager seperatly/redundant (because they are allready defined in the access-control-schema of each app) or should there be a mechanism so that the AM knows which groups are available in each application (might be tricky)?

**Comment by hohwille** [comment]
The toplevel access groups are defined by the applications. However an admin has to be able to grant users the according permissions by assigning the group. Therefore such group has to exist in a directory service and this is typically part of AM as this also contains the users and those have to be linked. 
So that kind of redundance is intended. It would be nice to have a tool that automatically creates these groups for the app from the access-control-schema (by selection of group type) and the technical application name/ID given. But that is a nice to have addon.
